"""Find trajectories and associated metadata

msmbuilder autogenerated template version 2
created 2017-03-03T20:42:01.986639
please cite msmbuilder in any publications


"""

from msmbuilder.io import gather_metadata, save_meta, NumberedRunsParser

## Construct and save the dataframe
parser = NumberedRunsParser(
    traj_fmt="trajectory-{run}.xtc",
    top_fn="top.pdb",
    step_ps=50,
)
meta = gather_metadata("trajs/*.xtc", parser)
save_meta(meta)