"""Check for abnormally high rmsd values to a reference structure

msmbuilder autogenerated template version 2
created 2017-03-03T20:42:02.015243
please cite msmbuilder in any publications


"""

import mdtraj as md

from msmbuilder.io import load_meta, itertrajs, save_trajs

## Load reference structure
ref = md.load("top.pdb")
meta = load_meta()

## Do calculation and save
rmsds = {k: md.rmsd(traj, ref) for k, traj in itertrajs(meta)}
save_trajs(rmsds, 'rmsds', meta)